version: "3.9"

services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: clothing_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  app-db-data:
